set_property PACKAGE_PIN U18 [get_ports ctr]
set_property PACKAGE_PIN U16 [get_ports r]
set_property PACKAGE_PIN U17 [get_ports rst]
set_property PACKAGE_PIN A14 [get_ports v]
set_property IOSTANDARD LVCMOS33 [get_ports ctr]
set_property IOSTANDARD LVCMOS33 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports v]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
