# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/petersLDlab/FP/voltage_level_test/voltage_level_test.cache/wt [current_project]
set_property parent.project_path D:/petersLDlab/FP/voltage_level_test/voltage_level_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/petersLDlab/FP/voltage_level_test/voltage_level_test.srcs/sources_1/new/voltage_level.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/petersLDlab/FP/voltage_level_test/voltage_level_test.srcs/constrs_1/new/voltage_level.xdc
set_property used_in_implementation false [get_files D:/petersLDlab/FP/voltage_level_test/voltage_level_test.srcs/constrs_1/new/voltage_level.xdc]


synth_design -top voltage_level -part xc7a35tcpg236-1


write_checkpoint -force -noxdef voltage_level.dcp

catch { report_utilization -file voltage_level_utilization_synth.rpt -pb voltage_level_utilization_synth.pb }
